@echo off
echo Adding Vercel environment variables for BFF production deployment...

echo Adding JWT_SECRET...
echo "super-secure-jwt-secret-key-for-shahin-grc-platform-2024" | vercel env add JWT_SECRET production

echo Adding JWT_REFRESH_SECRET...
echo "super-secure-jwt-refresh-secret-key-for-shahin-2024" | vercel env add JWT_REFRESH_SECRET production

echo Adding SERVICE_TOKEN...
echo "secure-service-token-for-internal-communication-32-chars" | vercel env add SERVICE_TOKEN production

echo Adding INTERNAL_SERVICE_TOKEN...
echo "internal-service-token-for-bff-communication-secure" | vercel env add INTERNAL_SERVICE_TOKEN production

echo Adding REDIS_URL...
echo "redis://default:password@redis-host:6379" | vercel env add REDIS_URL production

echo Adding FRONTEND_ORIGINS...
echo "https://app.shahin-ai.com,https://www.shahin-ai.com,https://shahin-ai.com" | vercel env add FRONTEND_ORIGINS production

echo Adding PUBLIC_BFF_URL...
echo "https://app.shahin-ai.com" | vercel env add PUBLIC_BFF_URL production

echo Adding NODE_ENV...
echo "production" | vercel env add NODE_ENV production

echo Adding PRODUCTION_MODE...
echo "true" | vercel env add PRODUCTION_MODE production

echo Adding SINGLE_TENANT_MODE...
echo "true" | vercel env add SINGLE_TENANT_MODE production

echo Adding BYPASS_AUTH...
echo "false" | vercel env add BYPASS_AUTH production

echo Adding RATE_LIMIT_WINDOW_MS...
echo "900000" | vercel env add RATE_LIMIT_WINDOW_MS production

echo Adding RATE_LIMIT_MAX_REQUESTS...
echo "100" | vercel env add RATE_LIMIT_MAX_REQUESTS production

echo Adding SSL_ENABLED...
echo "true" | vercel env add SSL_ENABLED production

echo Adding LOG_LEVEL...
echo "info" | vercel env add LOG_LEVEL production

echo Adding ENABLE_PERFORMANCE_MONITORING...
echo "true" | vercel env add ENABLE_PERFORMANCE_MONITORING production

echo Adding CSP_ENABLED...
echo "true" | vercel env add CSP_ENABLED production

echo Adding HSTS_MAX_AGE...
echo "31536000" | vercel env add HSTS_MAX_AGE production

echo Adding HSTS_INCLUDE_SUBDOMAINS...
echo "true" | vercel env add HSTS_INCLUDE_SUBDOMAINS production

echo Adding HSTS_PRELOAD...
echo "true" | vercel env add HSTS_PRELOAD production

echo Adding ENABLE_TRANSACTIONS...
echo "true" | vercel env add ENABLE_TRANSACTIONS production

echo Adding ENABLE_WORKFLOWS...
echo "true" | vercel env add ENABLE_WORKFLOWS production

echo Adding ENABLE_AUDIT_LOGGING...
echo "true" | vercel env add ENABLE_AUDIT_LOGGING production

echo All environment variables added successfully!
echo.
echo You can now deploy with: vercel --prod
echo.
pause